### ISSUE TITLE
[feature/place] Place View API 연결하기

### ISSUE THREAD

**Issue by minemi00** [SOPT-33RD-APP-NAVERPAY/NaverPay-Android#17]
## 📌 작업 내용
- [x] viewmodel에 서버 받아오기
- [x] viewmodel의 list observer로 전환시키기
- [x] submitlist 붙여주기
- [x] user랑 distance를 api로 받아주기 -> string가서 %로 받아주기

작업하면서 세세하게 추가해보겠습니다 !

## 💡참고 사항
https://www.notion.so/dosopt/_-8affadc9661841728362637c9c06f22f?pvs=4
PlaceView api 명세서입니다 -!

**Comment by librarywon** [comment]
끝났슴둥
